/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sat Jan 13 16:26:31 2018. */

#include "gate.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t be_lghs_gate_proto_GateOpenRequest_fields[5] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, be_lghs_gate_proto_GateOpenRequest, cardId, cardId, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, be_lghs_gate_proto_GateOpenRequest, tokenLow, cardId, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, be_lghs_gate_proto_GateOpenRequest, tokenHigh, tokenLow, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, be_lghs_gate_proto_GateOpenRequest, pin, tokenHigh, 0),
    PB_LAST_FIELD
};

const pb_field_t be_lghs_gate_proto_GateOpenResponse_fields[3] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, be_lghs_gate_proto_GateOpenResponse, cardId, cardId, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, be_lghs_gate_proto_GateOpenResponse, ok, cardId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
